- name: Deploy Excalidraw
  gather_facts: false
  hosts: all
  become: true

  tasks:
    - name: Create container
      ansible.builtin.copy:
        dest: /etc/containers/systemd/excalidraw.container
        content: |
          [Container]
          Image=docker.io/excalidraw/excalidraw
          Pull=always
          AutoUpdate=registry
          Network=caddy.network
          NetworkAlias=excalidraw

          [Service]
          Restart=always
          TimeoutStartSec=900

          [Install]   
          WantedBy=default.target
    - name: Start container
      ansible.builtin.systemd_service:
        daemon_reload: true
        service: excalidraw.service
        state: started
    - name: Create caddyfile
      notify: Restart caddy
      ansible.builtin.copy:
        dest: /etc/caddy/sites/draw
        content: |
          https://draw.apps.codatory.net {
            reverse_proxy http://excalidraw:80
          }

  handlers:
    - name: Restart caddy
      ansible.builtin.systemd_service:
        name: caddy.service
        state: stopped
