- name: Deploy Firefox
  gather_facts: false
  hosts: all
  become: true

  tasks:
    - name: Create volume
      ansible.builtin.copy:
        dest: /etc/containers/systemd/firefox.volume
        content: |
          [Volume]
    - name: Create container
      ansible.builtin.copy:
        dest: /etc/containers/systemd/firefox.container
        content: |
          [Container]
          Image=ghcr.io/jlesage/firefox
          Pull=always
          AutoUpdate=registry
          Volume=firefox.volume:/config
          Network=caddy.network
          NetworkAlias=firefox
          Environment='INSTALL_PACKAGES=msttcorefonts-installer font-terminus font-inconsolata font-dejavu font-noto font-noto-cjk font-awesome font-noto-extra'

          [Service]
          Restart=always
          TimeoutStartSec=900

          [Install]   
          WantedBy=default.target
    - name: Start container
      ansible.builtin.systemd_service:
        daemon_reload: true
        service: firefox.service
        state: started
    - name: Create caddyfile
      notify: Restart caddy
      ansible.builtin.copy:
        dest: /etc/caddy/sites/firefox
        content: |
          https://firefox.apps.codatory.net {
            reverse_proxy http://firefox:5800
          }

  handlers:
    - name: Restart caddy
      ansible.builtin.systemd_service:
        name: caddy.service
        state: stopped
