- name: Deploy IT Tools
  gather_facts: false
  hosts: all
  become: true

  tasks:
    - name: Create container
      ansible.builtin.copy:
        dest: /etc/containers/systemd/it-tools.container
        content: |
          [Container]
          Image=ghcr.io/corentinth/it-tools
          Pull=always
          AutoUpdate=registry
          Network=caddy.network
          NetworkAlias=it-tools

          [Service]
          Restart=always
          TimeoutStartSec=900

          [Install]   
          WantedBy=default.target
    - name: Start container
      ansible.builtin.systemd_service:
        daemon_reload: true
        service: it-tools.service
        state: started
    - name: Create caddyfile
      notify: Restart caddy
      ansible.builtin.copy:
        dest: /etc/caddy/sites/it-tools
        content: |
          https://it-tools.apps.codatory.net {
            reverse_proxy http://it-tools:80
          }

  handlers:
    - name: Restart caddy
      ansible.builtin.systemd_service:
        name: caddy.service
        state: stopped
