- name: Deploy MAZANOKE
  gather_facts: false
  hosts: all
  become: true

  tasks:
    - name: Create container
      ansible.builtin.copy:
        dest: /etc/containers/systemd/mazanoke.container
        content: |
          [Container]
          Image=ghcr.io/civilblur/mazanoke
          Pull=always
          AutoUpdate=registry
          Network=caddy.network
          NetworkAlias=mazanoke

          [Service]
          Restart=always
          TimeoutStartSec=900

          [Install]   
          WantedBy=default.target
    - name: Start container
      ansible.builtin.systemd_service:
        daemon_reload: true
        service: mazanoke.service
        state: started
    - name: Create caddyfile
      notify: Restart caddy
      ansible.builtin.copy:
        dest: /etc/caddy/sites/mazanoke
        content: |
          https://mazanoke.apps.codatory.net {
            reverse_proxy http://mazanoke:80
          }

  handlers:
    - name: Restart caddy
      ansible.builtin.systemd_service:
        name: caddy.service
        state: stopped
