- name: Apply sudo config
  hosts: all
  gather_facts: false
  vars_prompt:
    - name: ansible_become_password
      prompt: What is your password?
  become: true
  tasks:
    - name: Configure Sudo NoPasswd
      community.general.sudoers:
        name: sudoers-nopasswd
        state: present
        group: wheel
        commands: ALL
        nopassword: true
